version: '3.8'

services:
  codevinci-bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: codevinci-bot
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    command: python main.py
    restart: always
