version: '3.8'

services:
  bot:
    build: .
    container_name: codevincibot
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: always
